apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "wordpress,mysql"
type: Opaque
data:
  password: cGFzczEyMw==