apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-wordpress
  namespace: wordpress
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`web.etna.student`)
    services:
    - name: wordpress
      port: 80
  tls:
    secretName: tls-secret